---

- hosts: all
  gather_facts: no
  become: yes
  roles:
      - python
      - role: docker
        apt_release: main

      - role: docker_registery
        certs_path: "/tmp/"
        domain: everythingisawesome.com
