---

- name: make docker certs directory
  file:
      path: "{{certs_path}}"
      state: directory
      recurse: true
  tags:
      - debug

- name: create certs
  shell: |
      openssl req \
      -new \
      -newkey rsa:4096 \
      -nodes \
      -sha256 \
      -subj "/C=US" \
      -keyout {{certs_path}}/domain.key \
      -x509 \
      -days 365 \
      -out {{certs_path}}/domain.crt
  args:
    creates: "{{certs_path}}/domain.crt"
  tags:
      - debug


- name: start docker with TSL
  shell: echo "starting docker"
