---

- name: make docker certs directory
  file:
      path: "{{certs_path}}"
      state: directory
      recurse: true


- name: Make registry volume path
  file:
      path: "/volumes/{{domain}}"
      state: directory

- name: create auth directory
  file:
      path: "/auth"
      state: directory

- name: create certs
  shell: |
      openssl req \
      -newkey rsa:4096 \
      -nodes \
      -sha256 \
      -subj "/C=US" \
      -keyout {{certs_path}}/domain.key \
      -x509 \
      -days 365 \
      -out {{certs_path}}/domain.crt
  args:
    creates: "{{certs_path}}/domain.crt"

- name: pull docker registery image
  docker_image:
      name: registry
      tag: "{{registry_tag}}"


- name: make password file
  shell: docker run --name htpasswd registry:{{registry_tag}} /usr/bin/htpasswd -nbB {{user}} {{user_password}} > /auth/htpasswd
  tags:
      - create_user
      - debug


- name: start the registery
  docker_container:
      name: registry
      image: registry:{{registry_tag}}
      restart: true
      published_ports: 
          - "5000:5000"
      volumes:
          - "/auth/:/home"
          - "/volumes/{{domain}}:/var/lib/registry"
      env:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: "/home/htpasswd"
          REGISTRY_HTTP_TLS_CERTAIFICATE: "{{certs_path}}/domain.crt"
          REGISTRY_HTTP_TLS_KEY: "{{certs_path}}/domain.key"
  tags:
      - debug
          

